package domain;

// Generated 2017-4-2 9:22:29 by Hibernate Tools 3.4.0.CR1

/**
 * EmoWord generated by hbm2java
 */
public class EmoWord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7703799322781550025L;
	private Integer wid;
	private String word;
	private String type;
	private Integer meanNum;
	private Integer meanNo;
	private String emoType;
	private Integer intensity;
	private Integer polarity;
	private String subEmoType;
	private Integer subIntensity;
	private Integer subPolarity;

	public EmoWord() {
	}

	public EmoWord(String word, String type) {
		this.word = word;
		this.type = type;
	}

	public EmoWord(String word, String type, Integer meanNum, Integer meanNo,
			String emoType, Integer intensity, Integer polarity,
			String subEmoType, Integer subIntensity, Integer subPolarity) {
		this.word = word;
		this.type = type;
		this.meanNum = meanNum;
		this.meanNo = meanNo;
		this.emoType = emoType;
		this.intensity = intensity;
		this.polarity = polarity;
		this.subEmoType = subEmoType;
		this.subIntensity = subIntensity;
		this.subPolarity = subPolarity;
	}

	public Integer getWid() {
		return this.wid;
	}

	public void setWid(Integer wid) {
		this.wid = wid;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getMeanNum() {
		return this.meanNum;
	}

	public void setMeanNum(Integer meanNum) {
		this.meanNum = meanNum;
	}

	public Integer getMeanNo() {
		return this.meanNo;
	}

	public void setMeanNo(Integer meanNo) {
		this.meanNo = meanNo;
	}

	public String getEmoType() {
		return this.emoType;
	}

	public void setEmoType(String emoType) {
		this.emoType = emoType;
	}

	public Integer getIntensity() {
		return this.intensity;
	}

	public void setIntensity(Integer intensity) {
		this.intensity = intensity;
	}

	public Integer getPolarity() {
		return this.polarity;
	}

	public void setPolarity(Integer polarity) {
		this.polarity = polarity;
	}

	public String getSubEmoType() {
		return this.subEmoType;
	}

	public void setSubEmoType(String subEmoType) {
		this.subEmoType = subEmoType;
	}

	public Integer getSubIntensity() {
		return this.subIntensity;
	}

	public void setSubIntensity(Integer subIntensity) {
		this.subIntensity = subIntensity;
	}

	public Integer getSubPolarity() {
		return this.subPolarity;
	}

	public void setSubPolarity(Integer subPolarity) {
		this.subPolarity = subPolarity;
	}

}
