package domain;

// Generated 2017-4-21 15:56:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Psychology generated by hbm2java
 */
public class Psychology implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5489485118616633494L;
	private String uid;
	private Double neuroticism;
	private Double agreeableness;
	private Double extraversion;
	private Double conscientiousness;
	private Double openness;
	private Date judgeTime;

	public Psychology() {
	}

	public Psychology(String uid, Date judgeTime) {
		this.uid = uid;
		this.judgeTime = judgeTime;
	}

	public Psychology(String uid, Double neuroticism, Double agreeableness,
			Double extraversion, Double conscientiousness, Double openness,
			Date judgeTime) {
		this.uid = uid;
		this.neuroticism = neuroticism;
		this.agreeableness = agreeableness;
		this.extraversion = extraversion;
		this.conscientiousness = conscientiousness;
		this.openness = openness;
		this.judgeTime = judgeTime;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public Double getNeuroticism() {
		return this.neuroticism;
	}

	public void setNeuroticism(Double neuroticism) {
		this.neuroticism = neuroticism;
	}

	public Double getAgreeableness() {
		return this.agreeableness;
	}

	public void setAgreeableness(Double agreeableness) {
		this.agreeableness = agreeableness;
	}

	public Double getExtraversion() {
		return this.extraversion;
	}

	public void setExtraversion(Double extraversion) {
		this.extraversion = extraversion;
	}

	public Double getConscientiousness() {
		return this.conscientiousness;
	}

	public void setConscientiousness(Double conscientiousness) {
		this.conscientiousness = conscientiousness;
	}

	public Double getOpenness() {
		return this.openness;
	}

	public void setOpenness(Double openness) {
		this.openness = openness;
	}

	public Date getJudgeTime() {
		return this.judgeTime;
	}

	public void setJudgeTime(Date judgeTime) {
		this.judgeTime = judgeTime;
	}

}
