package domain;

// Generated 2017-4-25 14:41:52 by Hibernate Tools 3.4.0.CR1

/**
 * Quality generated by hbm2java
 */
public class Quality implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7301589671491475758L;
	private String uid;
	private Double accuracy;
	private Double effect;

	public Quality() {
	}

	public Quality(String uid) {
		this.uid = uid;
	}

	public Quality(String uid, Double accuracy, Double effect) {
		this.uid = uid;
		this.accuracy = accuracy;
		this.effect = effect;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public Double getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(Double accuracy) {
		this.accuracy = accuracy;
	}

	public Double getEffect() {
		return this.effect;
	}

	public void setEffect(Double effect) {
		this.effect = effect;
	}

}
