package domain;

// Generated 2017-4-21 15:39:33 by Hibernate Tools 3.4.0.CR1

/**
 * Relation generated by hbm2java
 */
public class Relation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2298480922983695642L;
	private Integer id;
	private String suid;
	private String tuid;
	private String tname;

	public Relation() {
	}

	public Relation(String suid, String tuid) {
		this.suid = suid;
		this.tuid = tuid;
	}

	public Relation(String suid, String tuid, String tname) {
		this.suid = suid;
		this.tuid = tuid;
		this.tname = tname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSuid() {
		return this.suid;
	}

	public void setSuid(String suid) {
		this.suid = suid;
	}

	public String getTuid() {
		return this.tuid;
	}

	public void setTuid(String tuid) {
		this.tuid = tuid;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

}
