package domain;

// Generated 2017-4-6 22:42:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Weibo generated by hbm2java
 */
public class Weibo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9189702234989780225L;
	private String mid;
	private Date date;
	private String text;
	private String source;
	private Integer repostsnum;
	private Integer commentsnum;
	private Integer attitudesnum;
	private String uid;
	private String topic;

	public Weibo() {
	}

	public Weibo(String mid, String text, String uid) {
		this.mid = mid;
		this.text = text;
		this.uid = uid;
	}

	public Weibo(String mid, Date date, String text, String source,
			Integer repostsnum, Integer commentsnum, Integer attitudesnum,
			String uid, String topic) {
		this.mid = mid;
		this.date = date;
		this.text = text;
		this.source = source;
		this.repostsnum = repostsnum;
		this.commentsnum = commentsnum;
		this.attitudesnum = attitudesnum;
		this.uid = uid;
		this.topic = topic;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Integer getRepostsnum() {
		return this.repostsnum;
	}

	public void setRepostsnum(Integer repostsnum) {
		this.repostsnum = repostsnum;
	}

	public Integer getCommentsnum() {
		return this.commentsnum;
	}

	public void setCommentsnum(Integer commentsnum) {
		this.commentsnum = commentsnum;
	}

	public Integer getAttitudesnum() {
		return this.attitudesnum;
	}

	public void setAttitudesnum(Integer attitudesnum) {
		this.attitudesnum = attitudesnum;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

}
